"""Initial schema - Property, Transaction, Document, Obligation, AuditLog

Revision ID: fcf071ccc323
Revises: 
Create Date: 2025-11-13 03:06:53.209186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fcf071ccc323'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_log_user'), 'audit_log', ['user'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=False),
    sa.Column('purchase_price_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('land_basis', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('building_basis', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ffe_basis', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('placed_in_service', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'UNDER_CONTRACT', 'SOLD', 'INACTIVE', name='propertystatus'), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_acquisition_date'), 'properties', ['acquisition_date'], unique=False)
    op.create_index(op.f('ix_properties_address'), 'properties', ['address'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=True),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('doc_type', sa.Enum('FORMATION', 'AUTHORITY', 'OPERATING_AGREEMENT', 'MINUTES', 'CONSENT', 'DEED', 'CLOSING', 'BANK_STATEMENT', 'CREDIT_CARD_STATEMENT', 'INVOICE', 'RECEIPT', 'INSURANCE_POLICY', 'INSURANCE_DECLARATION', 'INSURANCE_CLAIM', 'TAX_RETURN', 'TAX_EXTENSION', 'TAX_NOTICE', 'PERIODIC_REPORT', 'LEASE', 'VENDOR_CONTRACT', 'CORRESPONDENCE', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('version', sa.Enum('DRAFT', 'FINAL', 'SUPERSEDED', 'ARCHIVED', name='documentversion'), nullable=False),
    sa.Column('confidentiality', sa.Enum('PUBLIC', 'INTERNAL', 'RESTRICTED', name='documentconfidentiality'), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_doc_type'), 'documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_documents_effective_date'), 'documents', ['effective_date'], unique=False)
    op.create_index(op.f('ix_documents_property_id'), 'documents', ['property_id'], unique=False)
    op.create_table('obligations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=True),
    sa.Column('obligation_type', sa.Enum('TAX_FILING', 'TAX_PAYMENT', 'PERIODIC_REPORT', 'INSURANCE_RENEWAL', 'LICENSE_RENEWAL', 'RENT_PAYMENT', 'OTHER', name='obligationtype'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DUE_SOON', 'OVERDUE', 'COMPLETED', 'CANCELLED', name='obligationstatus'), nullable=False),
    sa.Column('recurrence', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obligations_due_date'), 'obligations', ['due_date'], unique=False)
    op.create_index(op.f('ix_obligations_obligation_type'), 'obligations', ['obligation_type'], unique=False)
    op.create_index(op.f('ix_obligations_property_id'), 'obligations', ['property_id'], unique=False)
    op.create_index(op.f('ix_obligations_status'), 'obligations', ['status'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.Enum('RENTAL_INCOME', 'UTILITIES_GAS', 'UTILITIES_WATER', 'UTILITIES_ELECTRIC', 'UTILITIES_INTERNET', 'UTILITIES_OTHER', 'REPAIRS_MAINTENANCE', 'CLEANING', 'SUPPLIES', 'INSURANCE_PROPERTY', 'INSURANCE_LIABILITY', 'INSURANCE_OTHER', 'PROPERTY_TAXES', 'PROPERTY_MANAGEMENT', 'PROFESSIONAL_ACCOUNTING', 'PROFESSIONAL_LEGAL', 'PROFESSIONAL_OTHER', 'BANK_FEES', 'INTEREST_EXPENSE', 'CREDIT_CARD_FEES', 'HOA_FEES', 'ADVERTISING', 'LICENSES_PERMITS', 'OFFICE_EXPENSE', 'TRAVEL', 'CAPITAL_IMPROVEMENT', 'FURNITURE_FIXTURES', 'BASIS_ADJUSTMENT', 'MEMBER_CONTRIBUTION', 'MEMBER_DISTRIBUTION', 'UNCATEGORIZED', name='transactioncategory'), nullable=False),
    sa.Column('transaction_type', sa.Enum('REVENUE', 'EXPENSE', 'CAPITAL', 'EQUITY', 'TRANSFER', name='transactiontype'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('source_account', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_category'), 'transactions', ['category'], unique=False)
    op.create_index(op.f('ix_transactions_property_id'), 'transactions', ['property_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_property_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_obligations_status'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_property_id'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_obligation_type'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_due_date'), table_name='obligations')
    op.drop_table('obligations')
    op.drop_index(op.f('ix_documents_property_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_effective_date'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_type'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_properties_address'), table_name='properties')
    op.drop_index(op.f('ix_properties_acquisition_date'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_audit_log_user'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
